Message.create(greeting: 'Hello, I am SekoViper.')
Message.create(greeting: 'Hi, I am SekoViper.')
Message.create(greeting: 'Hey, I am SekoViper.')
Message.create(greeting: 'Yo, I am SekoViper.')
Message.create(greeting: 'What\'s up?, I am SekoViper.')
